In [1]:
import numpy as np

# 1. Установить, какие произведения матриц AB и BA определены, и найти размерности полученных матриц:
а) A — матрица 4×2 , B — матрица 4×2 ;

б) A — матрица 2×5 , B — матрица 5×3 ;

в) A — матрица 8×3 , B — матрица 3×8 ;

г) A — квадратная матрица 4×4 , B — квадратная матрица 4×4 .

# 


а) нет
б) АВ 2х3
в) АВ 8х8 и ВА 3х3
г) АВ 4х4 и ВА 4х4

# 2. Найдите сумму и произведение матриц  

In [2]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
print(f'A+B:\n{A + B}\n')
print(f'A*B:\n{np.dot(A, B)}\n')
print(f'B*A:\n{np.dot(B, A)}')

A+B:
[[ 5 -3]
 [ 3  5]]

A*B:
[[  4 -11]
 [ 12  -3]]

B*A:
[[ 1 -8]
 [15  0]]


# 3. Вычислить линейную комбинацию 3A - 2B + 4C

In [4]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
print(f'3A-2B+4C:\n{3*A - 2*B + 4*C}\n')

3A-2B+4C:
[[ 11  -5]
 [  9 -12]]



# Дана матрица  . Вычислите  𝐴𝐴𝑇  и  𝐴𝑇𝐴 .

In [5]:
A = np.array([[4, 1], [5, -2], [2, 3]])
print(f'A:\n{A}\n')
print(f'A.T:\n{A.T}\n')
print(f'A*A.T:\n{np.dot(A, A.T)}\n')
print(f'A.T*A:\n{np.dot(A.T, A)}')

A:
[[ 4  1]
 [ 5 -2]
 [ 2  3]]

A.T:
[[ 4  5  2]
 [ 1 -2  3]]

A*A.T:
[[17 18 11]
 [18 29  4]
 [11  4 13]]

A.T*A:
[[45  0]
 [ 0 14]]


# 5*. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [9]:
a = [[4, 5, 2],
     [1, -2, 3]]
     
b = [[4, 1],
     [5,-2],
     [ 2, 3]]

In [10]:
m = len(a)                                            # a: m × n
n = len(b)                                            # b: n × k
k = len(b[0])

c = [[None for __ in range(k)] for __ in range(m)]    # c: m × k

for i in range(m):
    for j in range(k):       
        c[i][j] = sum(a[i][kk] * b[kk][j] for kk in range(n))
  
print(c)

[[45, 0], [0, 14]]


# взял матрицы из предыдущего задания

# 2 часть   Вычислить определитель:

In [11]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'A:\n{A}\n')
print(f'det:\n{round(np.linalg.det(A))}')

A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

det:
0


# Определитель матрицы A равен 4 . 

# Согласно свойствам определителя:
а) 
Для двух квадратных матриц одинакового размера
det(AB)=detA⋅detB
б)  Определитель транспонированной матрицы равен определителю исходной
в)  Умножение строки или столбца матрицы на число приведет к умножению определителя матрицы на то же число. Соответственно при умножении всей матрицы на число определитель будет зависеть от ее порядка (числа строк)

# Доказать, что матрица вырожденная

In [12]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'A:\n{A}\n')
print(f'det:\n{round(np.linalg.det(A))}')

A:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]

det:
0


# Вырожденная матрица - квадратная матрица, определитель которой равен 0.

# Найти ранг матрицы

In [14]:
A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
print(f'A:\n{A}\n')
print(f'rank:\n{round(np.linalg.matrix_rank(A))}')

A:
[[1 2 3]
 [1 1 1]
 [2 3 4]]

rank:
2


In [15]:
A = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
print(f'A:\n{A}\n')
print(f'rank:\n{round(np.linalg.matrix_rank(A))}')

A:
[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]

rank:
3
